### ISSUE TITLE
SLO Summaries don't get imported

### ISSUE THREAD

**Issue by WillPlatnick** [grosser/kennel#103]
Datadog has changed around their SLO widgets work. Previously they operated as widgets of their own. They've now apparently gotten rid of the SLO widget and replaced them with the SLO Summary widget, now that they're treating SLO's as first class objects.

When you do an import of a dashboard that has SLO Summary widgets, they don't appear.

**Comment by grosser** [comment]
yeah so all slo monitors are now just linked to slos or so ...

```
            {
              definition: {
                title: "[migrated] dash: fooo",
                type: "slo",
                add_timeframe: true,
                height: 19,
                isNew: false,
                isShared: false,
                legend: false,
                legend_size: "0",
                loading: true,
                react_header: true,
                show_component_uptimes: false,
                show_error_budget: true,
                show_viz: false,
                slo_id: "sdsdfdfsdfsdfs",
                time_windows: [
                  "7d"
                ],
                title_text: "[migrated] dash: foo",
                view_mode: "overall",
                view_type: "detail",
                viz: "slo",
                width: 60
              }
            },
```

**Comment by grosser** [comment]
diffing/planing seems to work with both ... so not really any problem
I tried adding a slo summary with the api and it worked fine ... also just keeping widgets also works fine

the only enhancement that would be nice is adding slo api support so they can be managed via kennel and then resolving them in the widgets by name

**Comment by grosser** [comment]
PR welcome to add slo support and then slo summary resolve support
I might do it if we end up wanting to use it, but not sure when that will be

**Comment by WillPlatnick** [comment]
That's very weird. I'm on kennel 1.56.0 and just did an import again on a dashboard with 3 SLO Summary widgets, via ```RESOURCE=dashboard ID=xxx-xxx-xxx rake kennel:import``` and what gets returned doesn't have any definitions for any slo's. The string slo doesn't exist in the whole output of what's returned.

**Comment by grosser** [comment]
Check what the raw api response is ... Maybe datadog has this enabled per
customer ...

**Comment by grosser** [comment]
If it's not there at all then open an issue with datadog support ... Kennel
can't do anything if the data is missing 😑

**Comment by WillPlatnick** [comment]
@grosser Can you provide  the returned dashboard json with the SLO Summary widget? Datadog support is saying it shouldn’t be returned in their current API.

**Comment by grosser** [comment]
tell them to look at dashboard ID qhy-94d-ub8 / https://api.datadoghq.com/api/v1/dashboard/qhy-94d-ub8 where I added a slo summary and slo widget
returns a `"type":"slo",` widget with an `slo_id` and a `"type":"uptime"`

**Comment by WillPlatnick** [comment]
@grosser if you just create a new dashboard, and ONLY the slo summary widget (not the SLO widget), do you get a JSON response that has the SLO widget?

**Comment by grosser** [comment]
works just as fine

```
  "widgets": [
    {
      "definition": {
        "board_id": "qhy-94d-ub8",
```

**Comment by WillPlatnick** [comment]
@grosser Datadog is saying it works for timeseries but not for screenboards. Can you tell me if you're getting an API response that includes SLO Summary widgets on a screenboard for you?

**Comment by grosser** [comment]
yep! ... screen boards do not support it / are empty :/
... talk with datadog support or simply don't use them in favor of using
the raw widgets ...
