### ISSUE TITLE
Importing a dashboard (pod => $pod) 

### ISSUE THREAD

**Issue by drhenner** [grosser/kennel#106]
I got this error when I followed the import dashboard

      ...  by {pod}.as_count() must use the template variables $pod

https://github.com/zendesk/kennel/pull/3023

**Comment by grosser** [comment]
yeah ... thats a validation to make sure all widgets update when the template variables are changed ... was one of the widgets not filterable by pod ? <-> does it need a better error message ?

**Comment by drhenner** [comment]
I thought when I'd run an import and follow the procedure I wouldn't get a validation error.  Is this something correctable in the import script or should be done manually each time?

**Comment by drhenner** [comment]
I guess I'm confused.  

my error message is `{pod}.as_count() must use the template variables $pod`

but the comment here https://github.com/zendesk/kennel/pull/3023/files#r358599632
says I should change the commented code to`#  cannot use template variable $pod in <fill me in>`

**Comment by grosser** [comment]
The importer could run validations and say "looks like this is invalid" and
then add the `validate: -> { false }` line
but I kinda like that it forces users to check what they are doing is sane
... the error message from the validation failing could mention `validate:
-> { false }` though to make that easier
