### ISSUE TITLE
Kennel doesn't seem to support Sentry queries

### ISSUE THREAD

**Issue by Tang8330** [grosser/kennel#111]
![image](https://user-images.githubusercontent.com/4412200/74891827-ce269680-533c-11ea-93f4-194fd7f23bbe.png)

### Commands (output from rake kennel:update_datadog)
```
rake aborted!
Error 400 during PUT /api/v1/monitor

response:
{"errors":["The value provided for parameter 'query' is invalid"]}
```

**Comment by grosser** [comment]
do an import of an existing monitor and then use that query ... if it does not work, let me know :)
`rake kennel:import TYPE=monitor ID=abc`

**Comment by Tang8330** [comment]
You mean this right? 
`RESOURCE=monitor ID=abc bundle exec rake kennel:import`

^ Same error as before


Calling it with `rake kennel:import TYPE=monitor ID=abc` returns `Call with RESOURCE=dash`

**Comment by grosser** [comment]
looks like datadog is not accepting their own output then :/

... can you do `bundle open kennel` and then put a `puts JSON.pretty_generate(attributes)` into `lib/kennel/api.rb` `def update` ... then run again and make sure the query look the same as in the export dialog in the datadog UI ... if yes, then please report to support@datadog.com that their api is not accepting that query :(

**Comment by Tang8330** [comment]
Hey, sorry just following up now. Tried just that, query is the same as export on the UI. I'll open a ticket with DD!

**Comment by grosser** [comment]
please leave the ticket number here so others can reference it, if more ppl run into this :)

**Comment by Tang8330** [comment]
Haha, they use Zendesk as well. Prob can't see, but here it is :) http://help.datadoghq.com/hc/requests/311357
