### ISSUE TITLE
kennel should not crash if an import "id" cannot be found

### ISSUE THREAD

**Issue by zdrve** [grosser/kennel#145]
Instead it should just ignore the ID and continuing creating a new object, perhaps with a warning.

This would make kennel more stable and eliminate one of the more common ways that `master` breaks, especially because right now when this happens it's _not_ a breakage as a result of a recent commit.

**Comment by grosser** [comment]
we could make it fail when a project filter is used or maybe we add "do not fail when running on master" and it fails otherwise
definitely need the warning and someone to hunt these down once in a while

PR welcome if you know how to fix

**Comment by zdrve** [comment]
I'm not sure it _ever_ needs to fail. Warnings, yes. Failures .... I don't see the need.

pseudocode of the direction I'm thinking of taking:
```
# syncer calls this "expected"
# want = {
#   has tracking_id;
#   might have id;
# }

# rubocop:disable Style/NegatedIfElseCondition
if !want.id

  # syncer calls this "actual"
  got = find_existing_by_tid(want.tracking_id)

  if got
    UPDATE
  else
    CREATE
  end

else # want.id

  # syncer calls these "actual"
  got_by_tid = find_existing_by_tid(want.tracking_id)
  got_by_id = find_existing_by_id(want.id)

  if !got_by_id
    warn "$type $TID has id=$id, but there is no such item. The property 'id' should be removed from $TID"

    if got_by_tid
      UPDATE
    else
      CREATE
    end

  else # got_by_id

    if !got_by_tid
      UPDATE (adopt) # aka import
    else

      # got_by_id && got_by_tid

      if got_by_id == got_by_tid
        UPDATE
      else
        # ??? What to do here.
        #
        # Maybe: UPDATE got_by_id (ignore got_by_tid)
        # - but the update would give the tid to a second item, so we'd have to remove the tid from got_by_tid
        #
        # So maybe better:
        warn "$type $tid has id=X, and while there is such an item, it has tracking id Y. The property 'id' should be removed from $TID"
        UPDATE got_by_tid (ignore got_by_id)
      end

    end

  end

end
# rubocop:enable Style/NegatedIfElseCondition

```

**Comment by grosser** [comment]
prefer if we start with just "id not found" and not also touch "id belongs to different kennel_id"

**Comment by zdrve** [comment]
OK, here's an alternative, simpler way of achieving something similar:

Change `ensure_all_ids_found` to check the "create" and the "update" lists separately:

- for "create", if the expected item has an "id", then warn that the id wasn't found, so an item will be created, not imported
- for "update", if the expected item has an "id", and the id doesn't equal the actual id, then warn that the id is superfluous and should be removed in the interest of tidiness

That's it.

**Comment by grosser** [comment]
- don't think we need to do anything for update since that was never an
issue, fail as before (also because something is fishy)
- create + project filter -> most likely working on a branch -> fix it
right there and don't commit / don't get into a "we have to guess what you
want" situation
- create + no filter -> most likely on mege -> warn so we don't crash and
make sure it goes to slack like the diff alert
