### ISSUE TITLE
remove need for method source location

### ISSUE THREAD

**Issue by grosser** [grosser/kennel#170]
see https://github.com/grosser/kennel/pull/167

**Comment by zdrve** [comment]
I don't quite understand these two issues. They seem to be in conflict with each other.

Is this issue #170 saying that we should no longer attempt to report which source code line a value came from? That makes #167 redundant if so.

**Comment by grosser** [comment]
this is a placeholder issue to get the PR merged/resolved
... I guess I can just close it since we have the PR

the general idea was to remove source_location in favor of capturing the caller when defining the project so we only have 1 way of dealing with source locations
