### ISSUE TITLE
widget[board_id] is not settable for screens

### ISSUE THREAD

**Issue by grosser** [grosser/kennel#18]
@clarkbab

need to figure out if:
 - it is settable via the api at all
 - how to ignore it during diffing since we cannot read it

**Comment by clarkbab** [comment]
@grosser, looks like we can set `board_id` via the API... For example, I updated one of the widget's `board_id` value to `100000` in the `zendesk_channels` project, ran `bundle exec rake kennel:update_datadog`, and then fetched the screen using Postman. `board_id` was returned as `100000`.

**Comment by clarkbab** [comment]
Seemed to work when I removed the `actual[:widgets].each { |w| w.delete :board_id }` line. 
![image](https://user-images.githubusercontent.com/18463586/39561188-766452f8-4ee7-11e8-897c-cbff61bbbd57.png)
