### ISSUE TITLE
Should the API always specify the subdomain?

### ISSUE THREAD

**Issue by Ataraxic** [grosser/kennel#300]
I followed the readme and attempted to get Kennel setup. 

Our datadog account only exists in us5. 

I couldn't get `bundle exec rake plan` to pass without errors despite setting the subdomain.

I noticed [here](https://github.com/grosser/kennel/blob/master/lib/kennel/api.rb#L21) that we specify the subdomain as app overriding the environment variable because we have the [||=](https://github.com/grosser/kennel/blob/master/lib/kennel/api.rb#L21) in Utils. 

I started a [branch](https://github.com/Ataraxic/kennel/pull/1) and the specs passed. Testing it locally worked for me. Let me know if this is something that would be helpful or if I have misunderstood something.

Thanks.

**Comment by grosser** [comment]
try not setting the subdomain if that works I need to update the docs
afaik subdomain is needed for some legacy accounts

**Comment by Ataraxic** [comment]
Hello, 
I unset the subdomain. Verified with pry in the gem and am getting 
![image](https://github.com/grosser/kennel/assets/9220647/d896390f-cd2e-4e0f-80cb-0705b71d0d2a)

Modifying the subdomain to be us5 works for me. I believe our DD account was created this year so I don't believe we are a "legacy" account. Happy to do some more exploration if I can. Lemme know.

**Comment by grosser** [comment]
does this maybe do the trick ?
```
url = Utils.path_to_url("", subdomain: ENV["DATADOG_SUBDOMAIN"] || "app")
```

... if yes I can see if it works for us too

**Comment by Ataraxic** [comment]
Yup yup.

**Comment by grosser** [comment]
confirmed that it's not needed ... was just a leftover from old code 🤷 
1.148.0
