### ISSUE TITLE
Composite monitors fail the "plan" phase.

### ISSUE THREAD

**Issue by zd-carmo** [grosser/kennel#67]
While creating a composite monitor, it is not possible to run the Plan phase. 
This is because it tries to use the "critical" value. - which is usually not defined in a composite monitor (it uses Boolean logic between other monitors to decide when to trigger each level of alerts).

It should be enough if we define the "Critical" property as nil in case the monitor is a composite one (so it won't need to be explicitly dealt with in the rb files).

**Comment by grosser** [comment]
sounds good, new logic should go into https://github.com/grosser/kennel/blob/735e9f2651135e8ed9f8f1608d90a4d696134f5b/lib/kennel/models/monitor.rb#L71

**Comment by grosser** [comment]
fixed in https://github.com/grosser/kennel/pull/84
