### ISSUE TITLE
PROJECT filter & tracking field error

### ISSUE THREAD

**Issue by fhuitelec** [grosser/kennel#71]
I've recently got an error when using the `PROJECT` filter:

> Updates with PROJECT= filter should not update message/description of resources with a set `id:`, since this makes them get deleted by a full update.
> Remove the `id:` to test them out, which will result in a copy being created and later deleted.

I'm having a hard time to figure out why you added this safeguard.

<details><summary>The current implementation does not offer more details.</summary>

<p>

https://github.com/grosser/kennel/blob/f032de3ca3dc6f1be29bfde30d45e0cece77fb76/lib/kennel/syncer.rb#L181-L188

</p>

</details>

>

Same for the initial PR that introduced this safeguard (https://github.com/grosser/kennel/pull/43): I still don't get it 🤔

Could you explain why this safeguard exists?

## A bit more about how I intend to use the `PROJECT` filter

For simplicity's sake, I want to be able to test a pull request and run a `kennel:update_datadog` on a specific branch.

Since the repository is shared among our company developers' community, using `PROJECT` would allow us to minimize the risk of updating/deleting Datadog resources on different PRs.

### Example

- Developer A is on branch `new-product-a-observability` which creates a monitor
- Developer B is on branch `small-fix-on-screenboard-b` which fixes a few typos on an existing screenboard

Scenario:

1. Developer A runs `kennel:update_datadog` on its branch `new-product-a-observability` and it creates its monitor
2. Developer A shares the monitor URL in its PR for showcase purposes & to ease their peer's review
3. Developer B runs `kennel:update_datadog` on its branch `small-fix-on-screenboard-b` to check a few tings
4. Developer A got their monitor deleted 🤷‍♂️

This is why using the `PROJECT` filter would allow to only update a specific project and not touch anything else.

---

I may not have the right mindset, though. Let me know if you see a better way to handle this kind of workflow or if kennel is not intended to be used this way.

Anyway, thank you in advance for your help and nice work on this tool!

**Comment by grosser** [comment]
Adding the kennel tracking `generated by kennel foo:bar` results in resources(monitor/dash/..) being  considered as "managed by kennel" so any other kennel run would try to them.

The check could be narrowed down to only block cases where the tracking is indeed removed or added and not just the field is changed.

**Comment by grosser** [comment]
https://github.com/grosser/kennel/pull/72 for narrowing down the check ... but it still won't allow adding or removing

**Comment by fhuitelec** [comment]
Thanks for the explanation and narrowing down the condition.

I've tried #72, works like a charm for just updating the fields containing the tracking ID 👌

> but it still won't allow adding or removing

This does not help the Developer eXperience but I get the consistency need.

I'd be happy to discuss the DX within this issue but since you answered my questions and provided me with a solution, I'm closing the issue 🚪

Thank you again, you were quite responsive and that's much appreciated!
