### ISSUE TITLE
error Kennel::Models::Base::ValidationError: riak:riak-disk-volume-predict query interval was , but must be one of 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 1d

### ISSUE THREAD

**Issue by opetrushka-zendesk** [grosser/kennel#89]
Error:
error Kennel::Models::Base::ValidationError: riak:riak-disk-volume-predict query interval was , but must be one of 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h, 1d

Imported a forecast based monitor
the query is
`  "query": "min(next_3mo):forecast(min:system.disk.free{hostgroup:riak,environment:production,device:/var/lib/riak} by {pod}, 'linear', 1, interval='120m', history='3mo', model='reactive') <= 0.0",`

Was trying intervals listed and many other things...
It seems the parsing is somehow broken not even looking at that parameter correctly...
(plus probably need to add more timing options or having a less strict test?)

By query is `projects/riak.rb`/`riak-disk-volume-predict`
but noticed it gets the same thing for `projects//container-scanner/monitors/container_scanner.rb`/`container-scanner-sqs-queue-is-projected-to-back-up`

p.s.s. There are a few `validate: -> { false }` and 0 issues here... (me reading doc.. )

**Comment by grosser** [comment]
fixed in 1.44.1
