### ISSUE TITLE
Missing groups ?

### ISSUE THREAD

**Issue by grosser** [grosser/kennel#95]
We're using Kennel to code our monitors and some of our dashboards. We noticed when importing some dashboards the groups are lost after we export them. Apparently there's no support for it, but it would be nice.
I wanted to ask if there's any plan to support groups (or if it's already implemented and I'm not aware of it). Otherwise, maybe we could create a pull request to incorporate it.

**Comment by grosser** [comment]
`RESOURCE=dashboard ID=abc bundle exec rake kennel:import`
Imports groups for me ... did that not work for you ?
how exactly does it look like ? ... are you using latest version ?

**Comment by gastonfournier** [comment]
Thanks! Let me verify that we don't have a version issue, otherwise I'll build a case example to reproduce the issue if any

**Comment by gastonfournier** [comment]
Hi @grosser I finally confirmed that it was a version issue, we're running this on a docker image which was not updating the latest sources.
I'm sending a PR to share the docker image in case you think is valuable.
